### ISSUE TITLE
Update cell/point data

### ISSUE THREAD

**Issue by davidcortesortuno** [prs513rosewood/uvw#7]
If I need to write a file multiple times, is there a way to update the cell or point data appended in a `Data` object? SO I can write the same VTK but with updated values (and possibly change the filename as well)

**Comment by prs513rosewood** [comment]
I've made changes so that changes in data occuring after the VTK file object instanciation are correctly written to file. However if the structure of the data changes (number of points, type, etc) you need to instanciate a new object. To change the filename, you could just `grid.filename = "new_filename.vtr"` I think.
